# Generated by Django 4.2.5 on 2023-10-21 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_repairorder_acceptedamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserestock',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
