# Generated by Django 4.2.5 on 2023-11-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_servicehistory_iscancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicehistory',
            name='startDate',
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='finishDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
