# Generated by Django 4.2.5 on 2023-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_repairorder_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='type',
            field=models.CharField(default='Шестеренка', max_length=50, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
