# Generated by Django 4.2.5 on 2023-11-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_repairorder_finish_until_repairorder_is_warranty_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            f"""
            DROP TABLE IF EXISTS app_{model_name}_search;
            CREATE VIRTUAL TABLE app_{model_name}_search USING FTS5({fields});
            INSERT INTO app_{model_name}_search
                SELECT {fields}
                FROM app_{model_name}
                {" WHERE deleted_at IS NULL" if has_deleted_at else ""};
            """,
            f"""
            DROP TABLE app_{model_name}_search;
            """
        ) for [model_name, has_deleted_at, fields] in [
            ["employee", False, "first_name,last_name,patronymic,passport_info,position,end_reason,password,username,email,id"],
            ["service", True, "name,id"],
            ["repairorder", True, "client_name,vehicle_manufacturer,vehicle_model,complaints,diagnostic_results,comments,id"],
            ["warehouseprovider", True, "name,contact_info,id"],
            ["warehouseitem", True, "name,type,id"]
        ]
    ]
