# Generated by Django 4.2.5 on 2023-11-30 09:49

from django.db import migrations, models
from app.models import *


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_repairorder_finish_until_repairorder_is_warranty_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            f"""
            CREATE VIRTUAL TABLE {model_name}_search USING FTS5({fields});
            INSERT INTO {model_name}_search({fields})
                SELECT {fields}
                FROM {model_name};
            """,
            f"""
            DROP TABLE {model_name}_search;
            """
        ) for model_name, fields in [
            [
                f"app_{model.__name__.lower()}",
                ', '.join([name for [name, value] in model.__dict__.items() if (value.__class__.__name__ == "DeferredAttribute" and isinstance(value.field, models.CharField)) or name == "id"])
            ] for model in [Employee, Service, RepairOrder, WarehouseProvider, WarehouseItem]
        ]
    ]
