# Generated by Django 4.2.5 on 2023-12-09 17:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_client_vehicle_remove_repairorder_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='ФИО', max_length=100, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
    ]
