# Generated by Django 4.2.5 on 2023-12-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_client_name_client_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicehistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouserestock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouseuse',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='warehouserestock',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='warehouseuse',
            name='deleted_at',
        ),
    ]
